export const config = {
    RPC_URL: 'https://test-rpc1.stafihub.io',
    REST_URL: 'https://test-rest-rpc1.stafihub.io',
    EXPLORER_URL: 'https://testnet-explorer.stafihub.io',
    STAKING_URL: 'https://test-staking.stafihub.io/stake',
    NETWORK_NAME: 'StaFiHub',
    NETWORK_TYPE: 'testnet',
    CHAIN_ID: 'stafihub-testnet-1',
    CHAIN_NAME: 'StaFiHub testnet-1',
    COIN_DENOM: 'FIS',
    COIN_MINIMAL_DENOM: 'ufis',
    COIN_DECIMALS: 6,
    PREFIX: 'stafi',
    COIN_TYPE: 118,
    COINGECKO_ID: '-',
    GAS_PRICE_STEP_LOW: 0.0025,
    GAS_PRICE_STEP_AVERAGE: 0.025,
    GAS_PRICE_STEP_HIGH: 0.04,
    FEATURES: ['stargate', 'ibc-transfer', 'no-legacy-stdTx', 'ibc-go'],
};
